# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raustin9/src/amphora/external/Mantis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raustin9/src/amphora/external/Mantis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\" \"lib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raustin9/src/amphora/external/Mantis/CMakeFiles /home/raustin9/src/amphora/external/Mantis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raustin9/src/amphora/external/Mantis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mantis

# Build rule for target.
mantis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mantis
.PHONY : mantis

# fast build rule for target.
mantis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mantis.dir/build.make CMakeFiles/mantis.dir/build
.PHONY : mantis/fast

#=============================================================================
# Target rules for targets named simple_server

# Build rule for target.
simple_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_server
.PHONY : simple_server

# fast build rule for target.
simple_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_server.dir/build.make CMakeFiles/simple_server.dir/build
.PHONY : simple_server/fast

#=============================================================================
# Target rules for targets named trantor

# Build rule for target.
trantor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trantor
.PHONY : trantor

# fast build rule for target.
trantor/fast:
	$(MAKE) $(MAKESILENT) -f external/trantor/CMakeFiles/trantor.dir/build.make external/trantor/CMakeFiles/trantor.dir/build
.PHONY : trantor/fast

examples/simple_server/src/main.o: examples/simple_server/src/main.cc.o
.PHONY : examples/simple_server/src/main.o

# target to build an object file
examples/simple_server/src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_server.dir/build.make CMakeFiles/simple_server.dir/examples/simple_server/src/main.cc.o
.PHONY : examples/simple_server/src/main.cc.o

examples/simple_server/src/main.i: examples/simple_server/src/main.cc.i
.PHONY : examples/simple_server/src/main.i

# target to preprocess a source file
examples/simple_server/src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_server.dir/build.make CMakeFiles/simple_server.dir/examples/simple_server/src/main.cc.i
.PHONY : examples/simple_server/src/main.cc.i

examples/simple_server/src/main.s: examples/simple_server/src/main.cc.s
.PHONY : examples/simple_server/src/main.s

# target to generate assembly for a file
examples/simple_server/src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_server.dir/build.make CMakeFiles/simple_server.dir/examples/simple_server/src/main.cc.s
.PHONY : examples/simple_server/src/main.cc.s

mantis/src/mantis.o: mantis/src/mantis.cc.o
.PHONY : mantis/src/mantis.o

# target to build an object file
mantis/src/mantis.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mantis.dir/build.make CMakeFiles/mantis.dir/mantis/src/mantis.cc.o
.PHONY : mantis/src/mantis.cc.o

mantis/src/mantis.i: mantis/src/mantis.cc.i
.PHONY : mantis/src/mantis.i

# target to preprocess a source file
mantis/src/mantis.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mantis.dir/build.make CMakeFiles/mantis.dir/mantis/src/mantis.cc.i
.PHONY : mantis/src/mantis.cc.i

mantis/src/mantis.s: mantis/src/mantis.cc.s
.PHONY : mantis/src/mantis.s

# target to generate assembly for a file
mantis/src/mantis.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mantis.dir/build.make CMakeFiles/mantis.dir/mantis/src/mantis.cc.s
.PHONY : mantis/src/mantis.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mantis"
	@echo "... simple_server"
	@echo "... trantor"
	@echo "... examples/simple_server/src/main.o"
	@echo "... examples/simple_server/src/main.i"
	@echo "... examples/simple_server/src/main.s"
	@echo "... mantis/src/mantis.o"
	@echo "... mantis/src/mantis.i"
	@echo "... mantis/src/mantis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

